version: '3.7'

services:
  web:
    restart: always
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./static_volume/:/staticfiles
      - ./media_volume/:/mediafiles
      - ./:/usr/src/
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env.db

volumes:
  static_volume:
  media_volume:
  postgres_data:
